version: "3"
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_DEFAULT_VHOST=test
